version: '3'

networks:
  default:
    name: datahub_network
    external: true

services:
  beeline:
    depends_on:
      - spark
    image: kmor76/spark:3.2.4_s3_hadoop3.3.1
    volumes:
      - ./data:/tmp/data/
    command: sleep 3600
  spark:
    depends_on:
      - minio
    image: kmor76/spark:3.2.4_s3_hadoop3.3.1
    ports: 
      - "10000:10000"
    volumes:
      - ./data:/tmp/data/
    command: > 
      bash -c 
      "/opt/spark/sbin/start-thriftserver.sh 
      --conf spark.hadoop.fs.s3a.endpoint=http://minio:9000 
      --conf spark.hadoop.fs.s3a.path.style.access=True 
      --conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem 
      --conf spark.hadoop.fs.s3a.access.key=lRzQo7Nr5Jg36n3nimDI 
      --conf spark.hadoop.fs.s3a.secret.key=jA5j0Yhp9LY3I9E7WwCsKYDOV738COT53pT8S4vI 
      --hiveconf hive.server2.thrift.port=10000 
      --hiveconf hive.server2.thrift.bind.host=0.0.0.0 
      --conf spark.jars.packages=io.acryl:datahub-spark-lineage:0.10.4 
      --conf spark.extraListeners=datahub.spark.DatahubSparkListener 
      --conf spark.datahub.rest.server=http://datahub-gms:8080
      --master local[*] && sleep 36000"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniominio
    command: server --console-address ":9001" /data

volumes:
  minio_storage: {}